### ISSUE TITLE
Can't open the project in Eclipse

### ISSUE THREAD

**Issue by mirvpgh** [MobileFirst-Platform-Developer-Center/Wishlist#2]
I get this error when trying to import the project into MobileFirst Studio/Eclipse:

```
[2015-12-23 20:29:14]             Unexpected error during upgrade: java.lang.Error: org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 6; The processing instruction 
target matching "[xX][mM][lL]" is not allowed. at com.worklight.upgrader.WLUpgradeEngine.reWriteProjectVersion(WLUpgradeEngine.java:881) 
at com.worklight.upgrader.WLUpgradeEngine.stampWithLatestVersion(WLUpgradeEngine.java:666) at com.worklight.upgrader.WLUpgradeEngine.upgradeProject(WLUpgradeEngine.java:177) 
at com.worklight.studio.plugin.upgrader.WLUpgraderWorkspaceJob.runInWorkspace(Unknown Source) at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38) 
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54) Caused by: org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 
6; The processing instruction target matching "[xX][mM][lL]" is not allowed. at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257) 
at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348) at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) 
at com.worklight.upgrader.util.XMLUtils.readXMLAsDocument(XMLUtils.java:75) at com.worklight.upgrader.WLUpgradeEngine.reWriteProjectVersion(WLUpgradeEngine.java:864) 
... 5 more 
[2015-12-23 20:29:15]             java.lang.Error: org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
```

**Comment by NathanHazout** [comment]
What exact versions of MobileFirst and Eclipse are you using?
Keep an eye out for a updated fix in the coming week which I think can fix this issue.

**Comment by mirvpgh** [comment]
I am using MobileFirst Studio 7.1 and Eclipse Luna 4.4.2. I tried many different ways to import the files into Eclipse and keep getting errors while it builds the workspace, specifically Null Pointer Exception, and so on. I wanted to use this sample in a lab at InterConnect 2016 and deadline is coming up fast!

**Comment by IdanAdar** [comment]
Make sure you're using the latest available Studio build from the Eclipse Marketplace - check for updates in Eclipse.

**Comment by mirvpgh** [comment]
I upgraded to Eclipse Mars, and updated MobileFirst Studio to the latest build available through Eclipse update. Still getting this error when I try to import the project:[2016-01-06 19:21:14]             Unexpected error during upgrade: java.lang.Error: org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 6; The processing instruction 
target matching "[xX][mM][lL]" is not allowed. at com.worklight.upgrader.WLUpgradeEngine.reWriteProjectVersion(WLUpgradeEngine.java:881) 
at com.worklight.upgrader.WLUpgradeEngine.stampWithLatestVersion(WLUpgradeEngine.java:666) at com.worklight.upgrader.WLUpgradeEngine.upgradeProject(WLUpgradeEngine.java:177) 
at com.worklight.studio.plugin.upgrader.WLUpgraderWorkspaceJob.runInWorkspace(Unknown Source) at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39) 
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) Caused by: org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 
6; The processing instruction target matching "[xX][mM][lL]" is not allowed. at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257) 
at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348) at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) 
at com.worklight.upgrader.util.XMLUtils.readXMLAsDocument(XMLUtils.java:75) at com.worklight.upgrader.WLUpgradeEngine.reWriteProjectVersion(WLUpgradeEngine.java:864) 
... 5 more 
[2016-01-06 19:21:15]             java.lang.Error: org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.

**Comment by IdanAdar** [comment]
There may be a residue bug with Eclipse Mars. I suggest that for now you will try with Eclipse Luna.

**Comment by maggix** [comment]
Hi, I had the same issue. 

I fixed it by looking at XML files contained in the project and moving the comments `<!-- -->` within the `<?xml` tags.

**Comment by IdanAdar** [comment]
The descriptor XML file now starts with the XML declaration.
